backend:
  name: github
  repo: melismae/whyreadnow

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path, required: true }
      - { name: uuid, label: UUID, widget: SimpleUUIDControl, required: false }
      - { name: date, label: Date, widget: date, required: true }
      - { name: title, label: Title, widget: string, required: true }
      - { name: description, label: Description, widget: markdown, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - { name: image, label: Thumbnail, widget: image, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: parentCategory, label: Parent Category, widget: select, required: true, options: ["Book", "Film", "Music", "Art", "Design", "Performance", "Article", "Game"], default: ["Book"] }
      - { name: subCategory, label: Sub-category, widget: list, multiple: true, allow_add: true }
      - name: "workDetails"
        label: "Work Details"
        widget: "list"
        required: true
        fields: 
            - { name: workTitle, label: Title, widget: string, required: true }
            - { name: genre, label: Genre, widget: list, required: true, multiple: true, allow_add: true }
            - name: "influenced"
              label: "Influenced"
              widget: "relation"
              collection: "creator"
              required: false
              multiple: true
              searchFields: ["creator.firstName", "creator.lastName", "creator.group"]
              value: "creator.id"
              displayFields: ["creator.firstName", "creator.lastName", "creator.group"]
            - name: "creator" 
              label: "Creator"
              widget: "list"
              required: true
              fields:
                  - { name: firstName, label: First Name, widget: string, required: false }
                  - { name: lastName, label: Last Name, widget: string, required: false }
                  - { name: group, label: Group, widget: string, required: false }
                  - { name: role, label: Role, widget: string, required: true }
                  - { name: id, label: ID, widget: SimpleUUIDControl, prefix: creator, required: false }
                  - { name: primary, label: Primary, widget: boolean, default: true }
              