backend:
  name: github
  repo: melismae/whyreadnow

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: date, required: true }
      - { name: title, label: Title, widget: string, required: true }
      - { name: description, label: Description, widget: text, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
      - { name: image, label: Thumbnail, widget: image, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: types, label: Types, widget: list, required: false }
